name: Run Daily at 23:00 BRT

on:
  workflow_dispatch:
  schedule:
    # Agendar o job para rodar todos os dias às 23:00 (horário de Brasília, UTC-3)
    - cron: '0 2 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      HABITIFY_API_KEY: ${{ secrets.HABITIFY_API_KEY }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Run the script
        run: |
          cd src
          python -m main
