name: Run Daily at 23:00 BRT

on:
  workflow_dispatch:
  schedule:
    # Agendar o job para rodar todos os dias às 23:00 (horário de Brasília, UTC-3)
    - cron: '0 2 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Usando Python 3.12

      - name: Clear pip cache
        run: |
          python -m pip cache purge  # Limpa o cache do pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt  # Instala dependências com a versão atualizada do pandas

      - name: Run the script
        run: |
          python -m main
